language: go
go:
  - 1.11.x
  - tip
env:
  - GO111MODULE=on
  - CODECOV_TOKEN="6344253f-7188-4981-8c17-419b753d7386"
install:
  - go get -v golang.org/x/lint/golint
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip