// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/prongbang/mvp/test_test/internal/test_test/api/auth"
	"github.com/prongbang/mvp/test_test/internal/test_test/api/forgot"
	"github.com/prongbang/mvp/test_test/internal/test_test/api/login"
	"github.com/prongbang/mvp/test_test/internal/test_test/api/otp"
	"github.com/prongbang/mvp/test_test/internal/test_test/database"
)

import (
	_ "time/tzdata"
)

// Injectors from wire.go:

func CreateAPI(dbDriver database.Drivers) API {
	dataSource := login.NewDataSource(dbDriver)
	repository := login.NewRepository(dataSource)
	useCase := login.NewUseCase(repository)
	handler := login.NewHandler(useCase)
	validate := login.NewValidate()
	router := login.NewRouter(handler, validate)
	authDataSource := auth.NewDataSource(dbDriver)
	authRepository := auth.NewRepository(authDataSource)
	authUseCase := auth.NewUseCase(authRepository)
	authHandler := auth.NewHandler(authUseCase)
	authValidate := auth.NewValidate()
	authRouter := auth.NewRouter(authHandler, authValidate)
	forgotDataSource := forgot.NewDataSource(dbDriver)
	forgotRepository := forgot.NewRepository(forgotDataSource)
	forgotUseCase := forgot.NewUseCase(forgotRepository)
	forgotHandler := forgot.NewHandler(forgotUseCase)
	forgotValidate := forgot.NewValidate()
	forgotRouter := forgot.NewRouter(forgotHandler, forgotValidate)
	otpDataSource := otp.NewDataSource(dbDriver)
	otpRepository := otp.NewRepository(otpDataSource)
	otpUseCase := otp.NewUseCase(otpRepository)
	otpHandler := otp.NewHandler(otpUseCase)
	otpValidate := otp.NewValidate()
	otpRouter := otp.NewRouter(otpHandler, otpValidate)
	apiRouters := NewRouters(router, authRouter, forgotRouter, otpRouter)
	apiAPI := NewAPI(apiRouters)
	return apiAPI
}
