// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package database

// Injectors from wire.go:

func NewDatabaseDriver() Drivers {
	mongoDriver := NewMongoDbDriver()
	databaseDrivers := NewDrivers(mongoDriver)
	return databaseDrivers
}
